site_name: Braindocs test
site_url: 'http://localhost/'
repo_url: 'https://github.com/jandradap/braindocs'
site_description: 'Versi√≥n 0.0.0'
site_author: 'Jorge Andrada Prieto'
copyright: 'Jorge Andrada Prieto GPLv3'
site_favicon: ./img/favicon.ico
pages:
- Home: index.md
- Example: example.md
theme: readthedocs
